# Generated by Django 3.1.5 on 2021-03-13 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210220_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deliver_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='welfare',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('0-2000', '2k以下'), ('2000-5000', '2k-5k'), ('5000-10000', '5k-10k'), ('10000-15000', '10k-15k'), ('15000-25000', '15k-25k'), ('25000-50000', '25k-50k'), ('50000-', '50k以上')], default='0-2000', max_length=50),
        ),
    ]
