# Generated by Django 3.1.5 on 2021-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210313_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='welfare',
            field=models.CharField(max_length=50),
        ),
    ]
