# Generated by Django 3.1.5 on 2021-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210313_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('new', '在校/应届'), ('0-3', '3 年以下'), ('3-5', '3-5 年'), ('5-10', '5-10 年'), ('10-', '10 年以上'), ('none', '无要求')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('0-2000', '2k 以下'), ('2000-5000', '2k-5k'), ('5000-10000', '5k-10k'), ('10000-15000', '10k-15k'), ('15000-25000', '15k-25k'), ('25000-50000', '25k-50k'), ('50000-', '50k 以上')], default='0-2000', max_length=50),
        ),
    ]
