# Generated by Django 3.1.5 on 2021-03-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210314_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
    ]
