# Generated by Django 3.1.5 on 2021-03-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210314_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_id',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
            preserve_default=False,
        ),
    ]
