# Generated by Django 3.1.5 on 2021-03-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210314_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_id',
        ),
    ]
