# Generated by Django 3.1.5 on 2021-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210314_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='financing',
            field=models.CharField(choices=[('none', '未融资'), ('angel', '天使轮'), ('a', 'A 轮'), ('b', 'B 轮'), ('c', 'C 轮'), ('d', 'D 轮以上'), ('d', 'D 轮以上'), ('listed', '上市公司'), ('not_need', '不需要融资')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='scale',
            field=models.CharField(choices=[('0-15', '少于 15 人'), ('15-50', '15 - 50 人'), ('50-150', '50 - 150 人'), ('150-500', '150 - 500 人'), ('500-2000', '500 - 2000 人'), ('2000-', '2000 人以上')], default='0-15', max_length=50),
        ),
    ]
