# Generated by Django 3.1.5 on 2021-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210314_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FilePathField(default='../assets/scau.jpeg'),
        ),
    ]
