# Generated by Django 3.1.5 on 2021-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(default='../assets/scau.jpeg'),
        ),
    ]
