# Generated by Django 2.0 on 2021-01-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollectResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itime', models.DateTimeField()),
                ('Iaddress', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Ebackground', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobHunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('HName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('Hname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('Ebackground', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('jobIntention', models.CharField(max_length=100)),
                ('job_hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.JobHunter')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='job_hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.JobHunter'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Job'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Resume'),
        ),
        migrations.AddField(
            model_name='collectresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Resume'),
        ),
        migrations.AddField(
            model_name='collectjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Job'),
        ),
        migrations.AddField(
            model_name='collectjob',
            name='job_counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.JobHunter'),
        ),
    ]
